const seedData={salary:37945.18,expenses:[{name:"Rent",amount:9000,category:"Housing"},{name:"Car Finance",amount:7024.25,category:"Transport"},{name:"Car Insurance",amount:1507.14,category:"Insurance"},{name:"Groceries",amount:3000,category:"Food"},{name:"Fuel",amount:2000,category:"Transport"},{name:"Gym",amount:845,category:"Health"},{name:"ChatGPT",amount:400,category:"Subscriptions"},{name:"Vitality",amount:429,category:"Health"},{name:"Netflix",amount:179,category:"Subscriptions"},{name:"Google One",amount:53,category:"Subscriptions"},{name:"Apple",amount:240,category:"Subscriptions"},{name:"Tracker",amount:268,category:"Transport"},{name:"Vehicle Maintenance",amount:399,category:"Transport"},{name:"Old Mutual",amount:182,category:"Insurance"},{name:"ZestLife",amount:199,category:"Insurance"},{name:"Other Insurance",amount:469,category:"Insurance"},{name:"Bank Fees",amount:350,category:"Banking"},{name:"Family Support",amount:1500,category:"Family"},{name:"Discovery Spending",amount:4000,category:"Lifestyle"}],transactions:[],investments:[{name:"Emergency Fund",value:0,contribution:0,target:60000},{name:"TFSA",value:0,contribution:0,target:500000},{name:"Unit Trusts",value:0,contribution:0,target:1000000},{name:"Provident Fund",value:0,contribution:4967.46,target:3000000}]};
let data=JSON.parse(localStorage.getItem("sihleFinanceData")||"null")||seedData;
const fmt=n=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(n||0);
const save=()=>localStorage.setItem("sihleFinanceData",JSON.stringify(data));
function monthlyExpenses(){return data.expenses.reduce((s,x)=>s+Number(x.amount),0)}
function render(){const exp=monthlyExpenses(),sur=data.salary-exp,rate=data.salary?sur/data.salary*100:0;netSalary.textContent=fmt(data.salary);monthlyExpensesEl.textContent=fmt(exp);monthlySurplus.textContent=fmt(sur);savingsRate.textContent=`${rate.toFixed(1)}%`;const used=Math.min(100,exp/data.salary*100);incomeUsedBar.style.width=`${used}%`;incomeUsedLabel.textContent=`${used.toFixed(1)}%`;adviceBox.textContent=sur>=10000?"Strong monthly surplus. Prioritise TFSA, emergency savings and diversified investments.":sur>=5000?"Your budget is workable, but keep Discovery and lifestyle spending controlled.":"Your surplus is tight. Reduce discretionary spending before adding new commitments.";topExpenses.innerHTML=[...data.expenses].sort((a,b)=>b.amount-a.amount).slice(0,5).map(x=>itemHTML(x.name,x.category,fmt(x.amount))).join("");expenseList.innerHTML=data.expenses.map((x,i)=>itemHTML(x.name,x.category,fmt(x.amount),`<button class="danger" onclick="removeExpense(${i})">Delete</button>`)).join("");const cats=[...new Set([...data.expenses.map(x=>x.category),...data.transactions.map(x=>x.category)])].sort();transactionCategoryFilter.innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join("");renderTransactions();investmentList.innerHTML=data.investments.map((x,i)=>{const pct=x.target?Math.min(100,x.value/x.target*100):0;return `<div class="list-item"><div><strong>${x.name}</strong><small>${fmt(x.value)} of ${fmt(x.target)} · ${fmt(x.contribution)}/month</small><div class="progress"><div style="width:${pct}%"></div></div></div><button class="danger" onclick="removeInvestment(${i})">Delete</button></div>`}).join("")}
function itemHTML(title,sub,amount,action=""){return `<div class="list-item"><div><strong>${title}</strong><small>${sub}</small></div><div><span class="amount">${amount}</span>${action}</div></div>`}
function renderTransactions(){const month=monthFilter.value,cat=transactionCategoryFilter.value;const rows=data.transactions.filter(x=>(!month||x.date.startsWith(month))&&(!cat||x.category===cat));transactionList.innerHTML=rows.length?rows.map(x=>itemHTML(x.description,`${x.date} · ${x.category} · ${x.account}`,fmt(x.amount),`<button class="danger" onclick="removeTransaction(${data.transactions.indexOf(x)})">Delete</button>`)).join(""):"<p>No transactions added for this filter.</p>"}
function removeExpense(i){data.expenses.splice(i,1);save();render()}function removeTransaction(i){data.transactions.splice(i,1);save();render()}function removeInvestment(i){data.investments.splice(i,1);save();render()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});
addExpenseBtn.onclick=()=>expenseDialog.showModal();expenseForm.onsubmit=e=>{if(e.submitter.value==="cancel")return;data.expenses.push({name:expenseName.value,amount:Number(expenseAmount.value),category:expenseCategory.value});save();expenseForm.reset();render()};
addTransactionBtn.onclick=()=>{transactionDate.value=new Date().toISOString().slice(0,10);transactionDialog.showModal()};transactionForm.onsubmit=e=>{if(e.submitter.value==="cancel")return;data.transactions.push({date:transactionDate.value,description:transactionDescription.value,category:transactionCategory.value,account:transactionAccount.value,amount:Number(transactionAmount.value)});save();transactionForm.reset();render()};
addInvestmentBtn.onclick=()=>investmentDialog.showModal();investmentForm.onsubmit=e=>{if(e.submitter.value==="cancel")return;data.investments.push({name:investmentName.value,value:Number(investmentValue.value),contribution:Number(investmentContribution.value),target:Number(investmentTarget.value)});save();investmentForm.reset();render()};
monthFilter.onchange=renderTransactions;transactionCategoryFilter.onchange=renderTransactions;
calculateDecision.onclick=()=>{const cost=Number(decisionCost.value),sur=data.salary-monthlyExpenses();if(!cost)return;const months=sur>0?cost/sur:Infinity;let cls="bad",msg="Not affordable from your current monthly cash flow.";if(months<=1){cls="good";msg=`Affordable from roughly ${months.toFixed(1)} month of surplus, provided your emergency fund remains intact.`}else if(months<=3){cls="warn";msg=`Save for about ${months.toFixed(1)} months before buying. Avoid using expensive credit.`}decisionResult.className=`decision-result ${cls}`;decisionResult.innerHTML=`<strong>${decisionItem.value||"Purchase"}:</strong> ${msg}`};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sihle-finance-backup.json";a.click()};
importInput.onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{data=JSON.parse(reader.result);save();render();alert("Data imported successfully.")}catch{alert("Invalid backup file.")}};reader.readAsText(f)};
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove("hidden")});installBtn.onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add("hidden")};
if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js");const monthlyExpensesEl=document.getElementById("monthlyExpenses");render();